name: Java Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test with Maven
    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up JDK21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test with Maven
        run: mvn -B clean verify

      - name: Archieve test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: java-workflow
          path: target/surefire-reports/
   

    



    
   
    
